spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bayzdelivery
    username: db_user
    password: 123qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 5s
      quiet-period: 1s

server:
  port: 8081
  servlet:
    context-path: /api
